build website:
    image: node:20-alpine
    script:
        - yarn install
        - yarn build

test website:
   script:
       - test -f build/index.html

unit test: 
    script:
        - yarn test