stages:
  - build
  - build test
  - unit test

build website:
    image: node:20-alpine
    stage: build
    artifacts:
      paths:
        - build
    script:
        - yarn install
        - yarn build

build test:
   stage: build test
   script:
       - test -f build/index.html

unit test: 
    image: node:20-alpine
    stage: unit test
    script:
        - yarn test