stages:
  - build
  - test

build website:
    image: node:20-alpine
    stage: build
    script:
        - yarn install
        - yarn build
    artifacts:
      paths:
        - build
        
test website:
   image: apline
   stage: test
   script:
       - test -f build/index.html

unit tests: 
    image: node:20-alpine
    stage: test
    script:
        - yarn install
        - yarn test